### PR TITLE
#49 Suggestion: Adopt Ducks proposal for easier organization of reducers and actions

### PR DESCRIPTION
**Pull request by mattak**
## TODO

- [x] Apply ducks style to Example/Counter
- [x] Apply ducks style to Example/List

### CODE REVIEW

**Comment by austinmao** [comment]
Ok, here is what I came up with:

Count:
```
using System.Collections.Generic;

namespace Unidux.Example.Counter
{
    public static class Count {

        // specify the possible types of actions
        public enum ActionType {
            Increment,
            Decrement
        }

        // actions must have a type and may include a payload
        public class Action {
            public ActionType actionType;
        }

        // reducers handle state changes
        public class Reducer {
            public static State Reduce(State state, Action action) {
                switch (action.actionType) {
                    case ActionType.Increment:
                        state.Count++;
                        break;
                    case ActionType.Decrement:
                        state.Count--;
                        break;
                }

                return state;
            }
        }

        // ActionCreators create actions and deliver payloads
        // in redux, you do not dispatch from the ActionCreator to allow
        // for easy testability
        public class ActionCreator {
            public static Action Increment() {
                // create new action instance
                Action action_ = new Action();
                // specify required actionType and optional payloads
                action_.actionType = ActionType.Increment;
                // return action to the reducer
                return action_;
            }

            public static Action Decrement() {
                Action action_ = new Action();
                action_.actionType = ActionType.Decrement;
                return action_;
            }
        }

        // BoundActionCreators are helper functions to dispatch action creators
        public class BoundActionCreator {
            public static void Increment() {
                Unidux.Instance.Store.Dispatch(ActionCreator.Increment());
            }

            public static void Decrement() {
                Unidux.Instance.Store.Dispatch(ActionCreator.Decrement());
            }
        }
    }
}
```

List:
```
namespace Unidux.Example.List
{
    public static class List {

        public enum ActionType {
            Add
        }

        public class Action {
            public ActionType actionType;
            public string text; // example payload
        }

        public class Reducer {
            public static State Reduce(State state, Action action) {
                switch (action.actionType) {
                    case ActionType.Add:
                        state.List.Texts.Add(action.text);
                        state.List.SetStateChanged();
                        break;
                }

                return state;
            }
        }

        public class ActionCreator {
            // notice how payload is passed in function
            public static Action Add(string text) {
                Action action_ = new Action();
                action_.actionType = ActionType.Add;
                // pass action payload to reducer
                action_.text = text;
                return action_;
            }
        }

        public class BoundActionCreator {
            public static void Add(string text) {
                Unidux.Instance.Store.Dispatch(ActionCreator.Add(text));
            }
        }
    }
}
```

**Comment by mattak** [comment]
I fixed it! How about this? @austinmao

**Comment by austinmao** [comment]
Looks great

**Comment by mattak** [comment]
OK! I merge it

**Pull request merged**
